name = "remix-cloudflare-workers"
main = "worker/index.ts"
compatibility_date = "2022-04-05"

account_id = ""
workers_dev = true

[site]
bucket = "./public"

[env.dev]
vars = {SESSION_SECRET = "should-be-secure-in-prod"}